# Generated by Django 4.0.4 on 2022-05-08 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('short_description', models.TextField(default='')),
                ('description', models.TextField(default='')),
                ('timing', models.DateTimeField()),
                ('venue', models.CharField(default='', max_length=250)),
                ('organizers', models.CharField(default='', max_length=1550)),
                ('poster', models.TextField(blank=True)),
                ('closed', models.BooleanField(default=False)),
            ],
        ),
    ]
