# Generated by Django 4.0.4 on 2022-05-08 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='poster_image',
            field=models.ImageField(blank=True, upload_to='poster_images'),
        ),
    ]
