# Generated by Django 4.0.4 on 2022-05-08 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_poster_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='poster',
        ),
    ]
