# Generated by Django 4.0.4 on 2022-05-08 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_remove_event_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='fee',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='prize',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='register_url',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('Per Head', 'per_head'), ('Per Team', 'per_team'), ('Per Submission', 'per_submission')], default='Per Head', max_length=250),
        ),
    ]
