# Generated by Django 4.0.4 on 2022-05-08 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_fee_event_prize_event_register_url_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='offline_register',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='register_url',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
