# Generated by Django 4.0.4 on 2022-05-14 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_event_offline_register_alter_event_register_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='organizers',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('Per Head', 'per_head'), ('Per Team', 'per_team'), ('Per Head In Team', 'per_head_team'), ('Per Submission', 'per_submission')], default='Per Head', max_length=250),
        ),
    ]
