# Generated by Django 4.0.4 on 2022-05-19 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_alter_event_organizers_alter_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='sold_out',
            field=models.BooleanField(default=False),
        ),
    ]
